### ISSUE TITLE
Some suggestions for xmake.lua 

### ISSUE THREAD

**Issue by waruqi** [avaicode/wTestC#1]
You can use plats("linux") instead of project.plat() == "linux" and use set_languages("c99", "cxx11")  for setting languages. 

It will have better compatibility for the new version of xmake(branch: dev)

: )

.e.g

    if modes("debug") then
        set_symbols("debug")
        set_optimize("none")
    end

    if modes("release") then
        set_symbols("hidden")
        set_optimize("fastest")
        set_strip("all")
    end

    add_target("wTestC")
        set_kind("shared")
        add_includedirs("./src")
        add_files("./src/*.c")
        add_files("./src/*.cpp")
        set_languages("cxx11")

    if plats("windows") then
        add_defines("WINDOWS_B")
        add_includedirs("./src/windows")
        add_files("./src/windows/*.c")
    end

    if plats("linux") then
        add_defines("LINUX_B")
        add_includedirs("./src/linux")
        add_files("./src/linux/*.c")
    end

**Comment by avaicode** [comment]
Thanks.Already updated.
New version seems much more wonderful.
