### ISSUE TITLE
Simplify xmake.lua

### ISSUE THREAD

**Issue by waruqi** [avaicode/wTestC#2]
You can use the following code to simplify your xmake.lua 

.e.g 

    if is_plat("windows", "mingw") then 
    end

It's  equivalent to `is_plat("windows") or is_plat("mingw")` .

Of course, this is just my suggestion. : )

**Comment by avaicode** [comment]
Wow.It's awesome.
I've never thought of using the way of list.
Maybe my lua skill is poor. :P
